Ecommerce_project/urls.py
from django.conf import settings
import statistics
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('reseller/', include('reseller.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
   
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from .import views

app_name = 'customer'

urlpatterns = [
    path('',views.customer_home,name='home'),
    path('login',views.customer_login,name='login'),
    path('myorder',views.customer_myorder,name='myorder'),
    path('my_wishlist',views.customer_mywishlist,name='mywhishlist'),
    path('modal',views.modal,name='modal'),
    path('login1',views.login1,name='login1'),
    path('signup',views.signup,name='signup'),
    path('product_details',views.product_details,name='productdetails'),
    path('my_account',views.customer_my_account,name='myaccount'),
    
]

customer/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    address = models.CharField(max_length=300)
    email = models.CharField(max_length=20)
    mobile = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

customer/views.py
from django.shortcuts import render,redirect

from customer.models import Customer
from reseller.models import Reseller

# Create your views here.
def customer_home(request):

    if request.method == 'POST':  # when user clicks submit button
        if 'c_signup' in request.POST:  # when customer signup is clicked 
            c_first_name = request.POST['c_fname'] # getting data from firstname textbox, here c_fname is the name attribute of firstname textbox
            c_last_name = request.POST['c_lname']
            c_address = request.POST['c_addrs']
            c_email = request.POST['c_email']
            c_mobile = request.POST['c_phno']
            c_password = request.POST['c_passwd']

            # in ORM, if we want to insert data into a table, 

            # 1. create an object of model class by passing values

            customer = Customer(
                first_name = c_first_name, 
                last_name = c_last_name,
                address = c_address,
                email = c_email,
                mobile = c_mobile,
                password = c_password)

                # 2. call save method 
            customer.save() # save() is equivalent to insert into tablename sql query

        if 'c_login' in request.POST:
            email = request.POST['c_user_id']
            password = request.POST['c_user_passwd']

            try:
                customer = Customer.objects.get(email = email, password = password)  # select * from tablename wher email = email and password = password
                request.session['c_id'] = customer.id

            except:
                error_msg = 'Invalid username or password'
                return render(request, 'customer/customer_home.html',{'error_msg':error_msg})


        if 's_signup' in request.POST:
            name = request.POST['s_name']
            address = request.POST['s_address']
            email = request.POST['s_email']
            mobile = request.POST['s_mobile']
            ac_holdername =  request.POST['s_acholder']
            ac_number = request.POST['s_account']
            ifsc = request.POST['s_ifsc']
            photo = request.FILES['s_pic']
            password = request.POST['s_password']

            reseller = Reseller(
                s_name = name, 
                address = address, 
                email = email, 
                mobile = mobile, 
                account_holder_name = ac_holdername, 
                account_number = ac_number,
                ifsc = ifsc, 
                upload_image = photo,
                password = password )

            reseller.save()

        if 'signin' in request.POST:
            s_email = request.POST['s_mail']
            s_password = request.POST['s_pass']
            print('data')

            try:

                print('test')
                reseller = Reseller.objects.get(email = s_email,password = s_password)#approve
                request.session['s_id'] = reseller.id
                return redirect("reseller:reseller_home")# redirect is used to redirect to html page in another module "here reseller module"
            except:
                error_msg = 'invalid username or password'
                return render(request,'customer/customer_home.html',{'error_msg':error_msg})


            

    return render(request,'customer/customer_home.html')

def customer_login(request):
    return render(request,'customer/login.html')

def customer_myorder(request):
    return render(request,'customer/myorder.html')

def customer_mywishlist(request):
    return render(request,'customer/my_wishlist.html')

def customer_category(request):
    return render(request,'customer/category.html')

def modal(request):
    return render(request,'customer/login_modal.html')

def login1(request):
    return render(request,'customer/login1.html')

def signup(request):
    return render(request,'customer/signup.html')

def product_details(request):
    return render(request,'customer/product_details.html')

def customer_my_account(request):
    return render(request,'customer/my_account.html')

customer/templates/customer/copy.html
<header class="header-style-1"> 
  
    <!-- ============================================== TOP MENU ============================================== -->
    <div class="top-bar animate-dropdown">
      <div class="container">
        <div class="header-top-inner">
          <div class="cnt-account">
            <ul class="list-unstyled">
              <li class="myaccount"><a href="my_account"><span>My Account</span></a></li>
              <li class="wishlist"><a href="my_wishlist"><span>Wishlist</span></a></li>
              <li class="header_cart hidden-xs"><a href=""><span>My Cart</span></a></li>
              <li class="check"><a href="myorder"><span>My order</span></a></li>
              <li class="login"><a href="login">Login</a></li>
            </ul>
          </div>
          <!-- /.cnt-account -->
          <!--  customer modal start  -->

          <!-- Button trigger modal -->



<!-- Modal -->

          <!--  customer modal end  -->

          <div class="cnt-block">
            <ul class="list-unstyled list-inline">
              <li class="dropdown dropdown-small"> <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"><span class="value">USD </span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">USD</a></li>
                  <li><a href="#">INR</a></li>
                  <li><a href="#">GBP</a></li>
                </ul>
              </li>
              <li class="dropdown dropdown-small lang"> <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"><span class="value">English </span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">English</a></li>
                  <li><a href="#">French</a></li>
                  <li><a href="#">German</a></li>
                </ul>
              </li>
            </ul>
            <!-- /.list-unstyled --> 
          </div>
          <!-- /.cnt-cart -->
          <div class="clearfix"></div>
        </div>
        <!-- /.header-top-inner --> 
      </div>
      <!-- /.container --> 
    </div>
    <!-- /.header-top --> 
    <!-- ============================================== TOP MENU : END ============================================== -->
    <div class="main-header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-3 logo-holder"> 
            <!-- ============================================================= LOGO ============================================================= -->
            <div class="logo"> <a href="home.html"> <img src="static/assets/images/logo.png" alt="logo"> </a> </div>
            <!-- /.logo --> 
            <!-- ============================================================= LOGO : END ============================================================= --> </div>
          <!-- /.logo-holder -->
          
          <div class="col-lg-7 col-md-6 col-sm-8 col-xs-12 top-search-holder"> 
            <!-- /.contact-row --> 
            <!-- ============================================================= SEARCH AREA ============================================================= -->
            <div class="search-area">
              <form>
                <div class="control-group">
                  <ul class="categories-filter animate-dropdown">
                    <li class="dropdown"> <a class="dropdown-toggle"  data-toggle="dropdown" href="category.html">Categories <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" >
                        <li class="menu-header">Computer</li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Clothing</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Electronics</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Shoes</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Watches</a></li>
                      </ul>
                    </li>
                  </ul>
                  <input class="search-field" placeholder="Search here..." />
                  <a class="search-button" href="#" ></a> </div>
              </form>
            </div>
            <!-- /.search-area --> 
            <!-- ============================================================= SEARCH AREA : END ============================================================= --> </div>
          <!-- /.top-search-holder -->
          
          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 animate-dropdown top-cart-row"> 
            <!-- ============================================================= SHOPPING CART DROPDOWN ============================================================= -->
            
            <div class="dropdown dropdown-cart"> <a href="#" class="dropdown-toggle lnk-cart" data-toggle="dropdown">
              <div class="items-cart-inner">
                <div class="basket">
                <div class="basket-item-count"><span class="count">2</span></div>
                <div class="total-price-basket"> <span class="lbl">Shopping Cart</span> <span class="value">$4580</span> </div>
                </div>
              </div>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <div class="cart-item product-summary">
                    <div class="row">
                      <div class="col-xs-4">
                        <div class="image"> <a href="detail.html"><img src="static/assets/images/products/p4.jpg" alt=""></a> </div>
                      </div>
                      <div class="col-xs-7">
                        <h3 class="name"><a href="index8a95.html?page-detail">Simple Product</a></h3>
                        <div class="price">$600.00</div>
                      </div>
                      <div class="col-xs-1 action"> <a href="#"><i class="fa fa-trash"></i></a> </div>
                    </div>
                  </div>
                  <!-- /.cart-item -->
                  <div class="clearfix"></div>
                  <hr>
                  <div class="clearfix cart-total">
                    <div class="pull-right"> <span class="text">Sub Total :</span><span class='price'>$600.00</span> </div>
                    <div class="clearfix"></div>
                    <a href="checkout.html" class="btn btn-upper btn-primary btn-block m-t-20">Checkout</a> </div>
                  <!-- /.cart-total--> 
                  
                </li>
              </ul>
              <!-- /.dropdown-menu--> 
            </div>
            <!-- /.dropdown-cart --> 
            
            <!-- ============================================================= SHOPPING CART DROPDOWN : END============================================================= --> </div>
          <!-- /.top-cart-row --> 
        </div>
        <!-- /.row --> 
        
      </div>
      <!-- /.container --> 
      
    </div>
    <!-- /.main-header --> 
    
    <!-- ============================================== NAVBAR ============================================== -->
    <div class="header-nav animate-dropdown">
      <div class="container">
        <div class="yamm navbar navbar-default" role="navigation">
          <div class="navbar-header">
         <button data-target="#mc-horizontal-menu-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> 
         <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          </div>
          <div class="nav-bg-class">
            <div class="navbar-collapse collapse" id="mc-horizontal-menu-collapse">
              <div class="nav-outer">
                <ul class="nav navbar-nav">
                  <li class="active dropdown"> <a href="{% url 'customer:home' %}">Home</a> </li>
                  <li class="dropdown yamm mega-menu"> <a href=" " data-hover="dropdown" class="dropdown-toggle" data-toggle="dropdown">Clothing</a>
                    
                  </li>
                  <li class="dropdown mega-menu"> 
                  <a href="category.html"  data-hover="dropdown" class="dropdown-toggle" data-toggle="dropdown">Electronics <span class="menu-label hot-menu hidden-xs">hot</span> </a>
                    
                  </li>
                  <li class="dropdown hidden-sm"> <a href="category.html">Health & Beauty <span class="menu-label new-menu hidden-xs">new</span> </a> </li>
                  <li class="dropdown hidden-sm"> <a href="category.html">Watches</a> </li>
                  <li class="dropdown"> <a href="contact.html">Jewellery</a> </li>
                  <li class="dropdown"> <a href="contact.html">Shoes</a> </li>
                  <li class="dropdown"> <a href="contact.html">Kids & Girls</a> </li>
                  
                  <li class="dropdown  navbar-right special-menu"> <a href="#">Become a seller</a> </li>
                </ul>
                <!-- /.navbar-nav -->
                <div class="clearfix"></div>
              </div>
              <!-- /.nav-outer --> 
            </div>
            <!-- /.navbar-collapse --> 
            
          </div>
          <!-- /.nav-bg-class --> 
        </div>
        <!-- /.navbar-default --> 
      </div>
      <!-- /.container-class --> 
      
    </div>
    <!-- /.header-nav --> 
    <!-- ============================================== NAVBAR : END ============================================== --> 
    
  </header>

customer/templates/customer/customer_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<meta name="keywords" content="MediaCenter, Template, eCommerce">
<meta name="robots" content="all">
<title>Marazzo premium HTML5 & CSS3 Template</title>
 <!-- bootstrap link -->
 <link src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
 <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>

<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="static/assets/css/bootstrap.min.css">

<!-- Customizable CSS -->
<link rel="stylesheet" href="static/assets/css/main.css">
<link rel="stylesheet" href="static/assets/css/blue.css">
<link rel="stylesheet" href="static/assets/css/owl.carousel.css">
<link rel="stylesheet" href="static/assets/css/owl.transitions.css">
<link rel="stylesheet" href="static/assets/css/animate.min.css">
<link rel="stylesheet" href="static/assets/css/rateit.css">
<link rel="stylesheet" href="static/assets/css/bootstrap-select.min.css">
<link rel="stylesheet" href="{% static 'assets/css/modal.css' %}">

<!-- Icons/Glyphs -->
<link rel="stylesheet" href="static/assets/css/font-awesome.css">

<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Barlow:200,300,300i,400,400i,500,500i,600,700,800" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body class="cnt-home">
<!-- ============================================== HEADER ============================================== -->
{% include 'customer/header.html' %}

<!-- ============================================== HEADER : END ============================================== -->
{% block content %}

{% endblock %}
         

<!-- ============================================================= FOOTER ============================================================= -->
{% include 'customer/footer.html' %}
<!-- ============================================================= FOOTER : END============================================================= --> 

<!-- For demo purposes – can be removed on production --> 

<!-- For demo purposes – can be removed on production : End --> 

<!-- JavaScripts placed at the end of the document so the pages load faster --> 
<script src="static/assets/js/jquery-1.11.1.min.js"></script> 
<script src="static/assets/js/bootstrap.min.js"></script> 
<script src="static/assets/js/bootstrap-hover-dropdown.min.js"></script> 
<script src="static/assets/js/owl.carousel.min.js"></script> 
<script src="static/assets/js/echo.min.js"></script> 
<script src="static/assets/js/jquery.easing-1.3.min.js"></script> 
<script src="static/assets/js/bootstrap-slider.min.js"></script> 
<script src="static/assets/js/jquery.rateit.min.js"></script> 
<script src="static/assets/js/lightbox.min.js"></script> 
<script src="static/assets/js/bootstrap-select.min.js"></script> 
<script src="static/assets/js/wow.min.js"></script> 
<script src="static/assets/js/scripts.js"></script>
</body>

</html>

customer/templates/customer/footer.html
<div class="row our-features-box">
    <div class="container">
     <ul>
       <li>
         <div class="feature-box">
           <div class="icon-truck"></div>
           <div class="content-blocks">We ship worldwide</div>
         </div>
       </li>
       <li>
         <div class="feature-box">
           <div class="icon-support"></div>
           <div class="content-blocks">call 
             +1 800 789 0000</div>
         </div>
       </li>
       <li>
         <div class="feature-box">
           <div class="icon-money"></div>
           <div class="content-blocks">Money Back Guarantee</div>
         </div>
       </li>
       <li>
         <div class="feature-box">
           <div class="icon-return"></div>
           <div class="content">30 days return</div>
         </div>
       </li>
       
     </ul>
   </div>
 </div>
       <!-- /.info-boxes --> 
       <!-- ============================================== INFO BOXES : END ============================================== --> 

<!-- ============================================================= FOOTER ============================================================= -->
<footer id="footer" class="footer color-bg">
 <div class="footer-bottom">
   <div class="container">
     <div class="row">
       <div class="col-xs-12 col-sm-6 col-md-3">
       <div class="address-block">
       
         <!-- /.module-heading -->
         
         <div class="module-body">
           <ul class="toggle-footer" style="">
             <li class="media">
               <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i class="fa fa-map-marker fa-stack-1x fa-inverse"></i> </span> </div>
               <div class="media-body">
                 <p>ThemesGround, 789 Main rd, Anytown, CA 12345 USA</p>
               </div>
             </li>
             <li class="media">
               <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i class="fa fa-mobile fa-stack-1x fa-inverse"></i> </span> </div>
               <div class="media-body">
                 <p> + (888) 123-4567 / + (888) 456-7890</p>
               </div>
             </li>
             <li class="media">
               <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i class="fa fa-envelope fa-stack-1x fa-inverse"></i> </span> </div>
               <div class="media-body"> <span><a href="#">marazzo@themesground.com</a></span> </div>
             </li>
           </ul>
         </div>
         </div>
         <!-- /.module-body --> 
       </div>
       <!-- /.col -->
       
       <div class="col-xs-12 col-sm-6 col-md-3">
         <div class="module-heading">
           <h4 class="module-title">Customer Service</h4>
         </div>
         <!-- /.module-heading -->
         
         <div class="module-body">
           <ul class='list-unstyled'>
             <li class="first"><a href="#" title="Contact us">My Account</a></li>
             <li><a href="#" title="About us">Order History</a></li>
             <li><a href="#" title="faq">FAQ</a></li>
             <li><a href="#" title="Popular Searches">Specials</a></li>
             <li class="last"><a href="#" title="Where is my order?">Help Center</a></li>
           </ul>
         </div>
         <!-- /.module-body --> 
       </div>
       <!-- /.col -->
       
       <div class="col-xs-12 col-sm-6 col-md-3">
         <div class="module-heading">
           <h4 class="module-title">Corporation</h4>
         </div>
         <!-- /.module-heading -->
         
         <div class="module-body">
           <ul class='list-unstyled'>
             <li class="first"><a title="Your Account" href="#">About us</a></li>
             <li><a title="Information" href="#">Customer Service</a></li>
             <li><a title="Addresses" href="#">Company</a></li>
             <li><a title="Addresses" href="#">Investor Relations</a></li>
             <li class="last"><a title="Orders History" href="#">Advanced Search</a></li>
           </ul>
         </div>
         <!-- /.module-body --> 
       </div>
       <!-- /.col -->
       
       <div class="col-xs-12 col-sm-6 col-md-3">
         <div class="module-heading">
           <h4 class="module-title">Why Choose Us</h4>
         </div>
         <!-- /.module-heading -->
         
         <div class="module-body">
           <ul class='list-unstyled'>
             <li class="first"><a href="#" title="About us">Shopping Guide</a></li>
             <li><a href="#" title="Blog">Blog</a></li>
             <li><a href="#" title="Company">Company</a></li>
             <li><a href="#" title="Investor Relations">Investor Relations</a></li>
             <li class=" last"><a href="contact-us.html" title="Suppliers">Contact Us</a></li>
           </ul>
         </div>
         <!-- /.module-body --> 
       </div>
     </div>
   </div>
 </div>
 <div class="copyright-bar">
   <div class="container">
     <div class="col-xs-12 col-sm-4 no-padding social">
       <ul class="link">
         <li class="fb pull-left"><a target="_blank" rel="nofollow" href="#" title="Facebook"></a></li>
         <li class="tw pull-left"><a target="_blank" rel="nofollow" href="#" title="Twitter"></a></li>
         <li class="googleplus pull-left"><a target="_blank" rel="nofollow" href="#" title="GooglePlus"></a></li>
         <li class="rss pull-left"><a target="_blank" rel="nofollow" href="#" title="RSS"></a></li>
         <li class="pintrest pull-left"><a target="_blank" rel="nofollow" href="#" title="PInterest"></a></li>
         <li class="linkedin pull-left"><a target="_blank" rel="nofollow" href="#" title="Linkedin"></a></li>
         <li class="youtube pull-left"><a target="_blank" rel="nofollow" href="#" title="Youtube"></a></li>
       </ul>
     </div>
     <div class="col-xs-12 col-sm-4 no-padding copyright"><a target="_blank" href="https://www.templateshub.net">Templates Hub</a> </div>
     <div class="col-xs-12 col-sm-4 no-padding">
       <div class="clearfix payment-methods">
         <ul>
           <li><img src="static/assets/images/payments/1.png" alt=""></li>
           <li><img src="static/assets/images/payments/2.png" alt=""></li>
           <li><img src="static/assets/images/payments/3.png" alt=""></li>
           <li><img src="static/assets/images/payments/4.png" alt=""></li>
           <li><img src="static/assets/images/payments/5.png" alt=""></li>
         </ul>
       </div>
       <!-- /.payment-methods --> 
     </div>
   </div>
 </div>
</footer>

customer/templates/customer/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In Form</title>
    <link rel="stylesheet" href="static/assets/css/login.css">
</head>

<body>
    <div class="wrapper login">
        <div class="container">
            <div class="col-left">
                <div class="login-text">
                    <h2>Welcome!</h2>
                    <p>Create your account.<br>For Free!</p>
                    <a href="signup" class="btn">Sign Up</a>
                </div>
            </div>

            <div class="col-right">
                <div class="login-form">
                    <h2>Login</h2>
                    <form action="">
                        <p>
                            <label>Username/Email address<span>*</span></label>
                            <input type="text" placeholder="Username or Email" required>
                        </p>
                        <p>
                            <label>Password<span>*</span></label>
                            <input type="password" placeholder="Password" required>
                        </p>
                        <p>
                            <input type="submit" value="Sign In">
                        </p>
                        <p>
                            <a href="">Forgot password?</a>
                        </p>

                    </form>
                </div>
            </div>

        </div>
    </div>
</body>

</html>

customer/templates/customer/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In Form</title>
    <link rel="stylesheet" href="static/assets/css/login.css">
</head>

<body>
    <div class="wrapper login">
        <div class="container">
            <div class="col-left">
                <div class="login-text">
                    <h2>Welcome!</h2>
                    <p>Create your account.<br>For Free!</p>
                    <a href="login" class="btn">Login</a>
                </div>
            </div>

            <div class="col-right">
                <div class="login-form">
                    <h2>Sign Up</h2>
                    <form action="">
                        <p>
                            <label>FirstName<span>*</span></label>
                            <input type="text" required>
                        </p>
                        <p>
                            <label>LastName<span>*</span></label>
                            <input type="text" required>
                        </p>
                        <p>
                            <label>Address<span>*</span></label>
                            <input type="text" required>
                        </p>
                        <p>
                            <label>Email<span>*</span></label>
                            <input type="text" required>
                        </p>
                        <p>
                            <label>Mobile No<span>*</span></label>
                            <input type="text" required>
                        </p>
                        <p>
                            <label>Password<span>*</span></label>
                            <input type="password" required>
                        </p>
                        <p>
                            <input type="submit" value="Sign Up">
                        </p>
                        

                    </form>
                </div>
            </div>

        </div>
    </div>
</body>

</html>