Ecommerce_project/urls.py
from django.conf import settings
import statistics
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('reseller/', include('reseller.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
   
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from .import views

app_name = 'customer'

urlpatterns = [
    path('',views.customer_home,name='home'),
    path('login',views.customer_login,name='login'),
    path('myorder',views.customer_myorder,name='myorder'),
    path('my_wishlist',views.customer_mywishlist,name='mywhishlist'),
    path('modal',views.modal,name='modal'),
    path('login1',views.login1,name='login1'),
    path('signup',views.signup,name='signup'),
    path('product_details',views.product_details,name='productdetails'),
    path('my_account',views.customer_my_account,name='myaccount'),
    
]

ecom_admin/urls.py
from django.urls import path
from .import views

app_name = 'ecom_admin'

urlpatterns = [
    path('adminhome',views.admin_home,name='admin_home'),
    path('approve_reseller',views.approve_reseller,name='approve_reseller'),
    path('change_password',views.change_password,name='changepass'),
    path('register_reseller',views.register_reseller,name='register_reseller'),
    path('admin_login',views.admin_login,name='admin_login'),
     

    

]

ecom_admin/models.py
from django.db import models

# Create your models here.
class AdminLogin(models.Model):
    admin_id = models.CharField(max_length=25)
    admin_password = models.CharField(max_length=30)

ecom_admin/views.py
from django.shortcuts import render

# Create your views here.

def admin_home(request):
    return render(request,'ecom_admin/admin_home.html')

def approve_reseller(request):
    return render(request,'ecom_admin/approve_resellers.html')

def change_password(request):
    return render(request,'ecom_admin/change_password.html')

def register_reseller(request):
    return render(request,'ecom_admin/register_reseller.html')

def admin_login(request):
    
    return render(request,'ecom_admin/admin_login.html')

ecom_admin/templates/ecom_admin/admin_home.html
{% extends 'ecom_admin/admin_master.html' %}
{% load static %}


{% block content %}

<p class="welcome"> Welcome Admin </p>
{% endblock %}

ecom_admin/templates/ecom_admin/admin_login.html
{% load static %}
<!DOCTYPE html>    
<html>    
<head>    
    <title>Login Form</title>    
    <link rel="stylesheet" href="static/assets/css/login.css">  
    <style>
        body{
            padding-top: 150px;
            
        }
        #log1{
            width: 500px;
            height: 350px;
            background-color: rgb(167, 165, 163);
            padding-top: 30px;
        }
        #log{
            width: 150px;
            height: 30px;
            background-color: rgb(170, 14, 232);
            color: white;
            border: none;
            
        }
    </style>  
</head>    
<body> <center>  
    <div id="log1"> 
    <h1 style="color: brown;">Login Page</h1><br>    
    <div class="login">    
    <form id="login" method="POST" >  
        {}  
        <label><b>User Name   <br> <br> 
        </b>    
        </label>    
        <input type="text" name="Uname" id="Uname" placeholder="Username">    
        <br><br>    
        <label><b>Password     <br><br>
        </b>    
        </label>    
        <input type="Password" name="Pass" id="Pass" placeholder="Password">    
        <br><br>    <br>
        <!-- <input type="button" name="log" id="log" value="Log In Here">        -->
        <a href="{% url 'ecom_admin:admin_home' %}" >login</a>
        <br><br>    
           
    </form>
</div>     
</div> 
</center>
</body>    
</html> 

ecom_admin/templates/ecom_admin/approve_resellers.html
    {% extends 'ecom_admin/admin_master.html' %}
    {% load static %}
    {% block content %}
    <style>
        table, th, td {
          border:1px solid black;
        }
        </style>
    



    <center><h1 style="color: brown;">APPROVE RESELLERS</center></h1>
    <table border="2" width="100%" >
        
   
        <tr>
            <th>SL.NO</th>
            <TH>ORDER DATE</TH>
            <TH>PRODUCT.NO</TH>
            <TH>PRODUCT NAME</TH>
            <TH>CUSTOMER NAME</TH>
            <TH>MOBILE NO</TH>
            <TH>SHIPPING ADDRESS</TH>
            <TH>QTY</TH>
            <TH>TOTAL AMOUNT</TH>
        </tr>
        <tr>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
        </tr>
        
    </table>

    {% endblock %}

ecom_admin/templates/ecom_admin/change_password.html
{% extends 'ecom_admin/admin_master.html' %}
{% load static %}


{% block content %}
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
<div class="row">
<div class="col-sm-12">
<h1 style="color: brown;"><center> Change Password</h1></center>
</div>
</div>
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
<form method="post" id="passwordForm">
    <input type="password" class="input-lg form-control" name="password2" id="password2" placeholder="old Password" autocomplete="off"><br><br>
<input type="password" class="input-lg form-control" name="password1" id="password1" placeholder="New Password" autocomplete="off"><br><br>
<!-- <div class="row">
<div class="col-sm-6">
<span id="8char" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 8 Characters Long<br>
<span id="ucase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Uppercase Letter
</div>
<div class="col-sm-6">
<span id="lcase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Lowercase Letter<br>
<span id="num" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Number
</div>
</div> -->
<input type="password" class="input-lg form-control" name="password2" id="password2" placeholder="Repeat Password" autocomplete="off"><br><br>
<!-- <div class="row">
<div class="col-sm-12">
<span id="pwmatch" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> Passwords Match
</div>
</div> -->
<div class="btn">
<input type="submit" class="col-xs-12 btn btn-primary btn-load btn-lg" data-loading-text="Changing Password..." value="Change Password">
</div>
</form>
</div><!--/col-sm-6-->
</div><!--/row-->
<script src="/staic/assets/js/password.js"></script>
{% endblock %}

ecom_admin/templates/ecom_admin/footer.html
{% load static %}
<!-- ============================================== INFO BOXES ============================================== -->
 
       <!-- /.info-boxes --> 
       <!-- ============================================== INFO BOXES : END ============================================== --> 


<footer id="footer" class="footer color-bg">
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="address-block">
          
            <!-- /.module-heading -->
            
            <div class="module-body">
              <ul class="toggle-footer" style="">
                <li class="media">
                  <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i class="fa fa-map-marker fa-stack-1x fa-inverse"></i> </span> </div>
                  <div class="media-body">
                    <p>ThemesGround, 789 Main rd, Anytown, CA 12345 USA</p>
                  </div>
                </li>
                <li class="media">
                  <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i class="fa fa-mobile fa-stack-1x fa-inverse"></i> </span> </div>
                  <div class="media-body">
                    <p> + (888) 123-4567 / + (888) 456-7890</p>
                  </div>
                </li>
                <li class="media">
                  <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i class="fa fa-envelope fa-stack-1x fa-inverse"></i> </span> </div>
                  <div class="media-body"> <span><a href="#">marazzo@themesground.com</a></span> </div>
                </li>
              </ul>
            </div>
            </div>
            <!-- /.module-body --> 
          </div>
          <!-- /.col -->
          
          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="module-heading">
              <h4 class="module-title">Customer Service</h4>
            </div>
            <!-- /.module-heading -->
            
            <div class="module-body">
              <ul class='list-unstyled'>
                <li class="first"><a href="#" title="Contact us">My Account</a></li>
                <li><a href="#" title="About us">Order History</a></li>
                <li><a href="#" title="faq">FAQ</a></li>
                <li><a href="#" title="Popular Searches">Specials</a></li>
                <li class="last"><a href="#" title="Where is my order?">Help Center</a></li>
              </ul>
            </div>
            <!-- /.module-body --> 
          </div>
          <!-- /.col -->
          
          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="module-heading">
              <h4 class="module-title">Corporation</h4>
            </div>
            <!-- /.module-heading -->
            
            <div class="module-body">
              <ul class='list-unstyled'>
                <li class="first"><a title="Your Account" href="#">About us</a></li>
                <li><a title="Information" href="#">Customer Service</a></li>
                <li><a title="Addresses" href="#">Company</a></li>
                <li><a title="Addresses" href="#">Investor Relations</a></li>
                <li class="last"><a title="Orders History" href="#">Advanced Search</a></li>
              </ul>
            </div>
            <!-- /.module-body --> 
          </div>
          <!-- /.col -->
          
          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="module-heading">
              <h4 class="module-title">Why Choose Us</h4>
            </div>
            <!-- /.module-heading -->
            
            <div class="module-body">
              <ul class='list-unstyled'>
                <li class="first"><a href="#" title="About us">Shopping Guide</a></li>
                <li><a href="#" title="Blog">Blog</a></li>
                <li><a href="#" title="Company">Company</a></li>
                <li><a href="#" title="Investor Relations">Investor Relations</a></li>
                <li class=" last"><a href="contact-us.html" title="Suppliers">Contact Us</a></li>
              </ul>
            </div>
            <!-- /.module-body --> 
          </div>
        </div>
      </div>
    </div>
    <div class="copyright-bar">
      <div class="container">
        <div class="col-xs-12 col-sm-4 no-padding social">
          <ul class="link">
            <li class="fb pull-left"><a target="_blank" rel="nofollow" href="#" title="Facebook"></a></li>
            <li class="tw pull-left"><a target="_blank" rel="nofollow" href="#" title="Twitter"></a></li>
            <li class="googleplus pull-left"><a target="_blank" rel="nofollow" href="#" title="GooglePlus"></a></li>
            <li class="rss pull-left"><a target="_blank" rel="nofollow" href="#" title="RSS"></a></li>
            <li class="pintrest pull-left"><a target="_blank" rel="nofollow" href="#" title="PInterest"></a></li>
            <li class="linkedin pull-left"><a target="_blank" rel="nofollow" href="#" title="Linkedin"></a></li>
            <li class="youtube pull-left"><a target="_blank" rel="nofollow" href="#" title="Youtube"></a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 no-padding copyright"><a target="_blank" href="https://www.templateshub.net">Templates Hub</a> </div>
        <div class="col-xs-12 col-sm-4 no-padding">
          <div class="clearfix payment-methods">
            <ul>
              <li><img src="{% static 'images/payments/1.png' %}" alt=""></li>
              <li><img src="{% static 'images/payments/2.png' %}" alt=""></li>
              <li><img src="{% static 'images/payments/3.png' %}" alt=""></li>
              <li><img src="{% static 'images/payments/4.png' %}" alt=""></li>
              <li><img src="{% static 'images/payments/5.png' %}" alt=""></li>
            </ul>
          </div>
          <!-- /.payment-methods --> 
        </div>
      </div>
    </div>
  </footer>

ecom_admin/templates/ecom_admin/header.html
{% load static %}
<header class="header-style-1"> 
  
    <!-- ============================================== TOP MENU ============================================== -->
    <div class="top-bar animate-dropdown">
      <div class="container">
        <div class="header-top-inner">
        
          
          <div class="cnt-block">
            <ul class="list-unstyled list-inline">
              <li class="dropdown dropdown-small"> <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"><span class="value">USD </span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">USD</a></li>
                  <li><a href="#">INR</a></li>
                  <li><a href="#">GBP</a></li>
                </ul>
              </li>
              <li class="dropdown dropdown-small lang"> <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"><span class="value">English </span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">English</a></li>
                  <li><a href="#">French</a></li>
                  <li><a href="#">German</a></li>
                </ul>
              </li>
            </ul>
            <!-- /.list-unstyled --> 
          </div>
          <!-- /.cnt-cart -->
          <div class="clearfix"></div>
        </div>
        <!-- /.header-top-inner --> 
      </div>
      <!-- /.container --> 
    </div>
    <!-- /.header-top --> 
    <!-- ============================================== TOP MENU : END ============================================== -->
    <div class="main-header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-3 logo-holder"> 
            <!-- ============================================================= LOGO ============================================================= -->
            {% comment %}
            <div class="logo">  logo here</div>
            {% endcomment %}
            <!-- /.logo --> 
            <!-- ============================================================= LOGO : END ============================================================= --> </div>
          <!-- /.logo-holder -->
          
          <div class="col-lg-7 col-md-6 col-sm-8 col-xs-12 top-search-holder"> 
            <!-- /.contact-row --> 
            <!-- ============================================================= SEARCH AREA ============================================================= -->
            <div class="search-area">
              <form>
                <div class="control-group">
                  <ul class="categories-filter animate-dropdown">
                    <li class="dropdown"> <a class="dropdown-toggle"  data-toggle="dropdown" href="category.html">Categories <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" >
                        <li class="menu-header">Computer</li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Clothing</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Electronics</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Shoes</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="category.html">- Watches</a></li>
                      </ul>
                    </li>
                  </ul>
                  <input class="search-field" placeholder="Search here..." />
                  <a class="search-button" href="#" ></a> </div>
              </form>
            </div>
            <!-- /.search-area --> 
            <!-- ============================================================= SEARCH AREA : END ============================================================= --> </div>
          <!-- /.top-search-holder -->
          
          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 animate-dropdown top-cart-row"> 
            <!-- ============================================================= SHOPPING CART DROPDOWN ============================================================= -->
            
            <div class="dropdown dropdown-cart"> <a href="#" class="dropdown-toggle lnk-cart" data-toggle="dropdown">
              <div class="items-cart-inner">
                <div class="basket">
                <div class="basket-item-count"><span class="count">2</span></div>
                <div class="total-price-basket"> <span class="lbl">Recent Orders</span> <span class="value">2 Nos</span> </div>
                </div>
              </div>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <div class="cart-item product-summary">
                    <div class="row">
                      <div class="col-xs-4">
                        <div class="image"> <a href="detail.html"><img src="{% static 'images/products/p4.jpg' %}" alt=""></a> </div>
                      </div>
                      <div class="col-xs-7">
                        <h3 class="name"><a href="index8a95.html?page-detail">Simple Product</a></h3>
                        <div class="price">$600.00</div>
                      </div>
                      <div class="col-xs-1 action"> <a href="#"><i class="fa fa-trash"></i></a> </div>
                    </div>
                  </div>
                  <!-- /.cart-item -->
                  <div class="clearfix"></div>
                  <hr>
                  <div class="clearfix cart-total">
                    <div class="pull-right"> <span class="text">Sub Total :</span><span class='price'>$600.00</span> </div>
                    <div class="clearfix"></div>
                    <a href="checkout.html" class="btn btn-upper btn-primary btn-block m-t-20">Checkout</a> </div>
                  <!-- /.cart-total--> 
                  
                </li>
              </ul>
              <!-- /.dropdown-menu--> 
            </div>
            <!-- /.dropdown-cart --> 
            
            <!-- ============================================================= SHOPPING CART DROPDOWN : END============================================================= --> </div>
          <!-- /.top-cart-row --> 
        </div>
        <!-- /.row --> 
        
      </div>
      <!-- /.container --> 
      
    </div>
    <!-- /.main-header --> 
    
    <!-- ============================================== NAVBAR ============================================== -->
    <div class="header-nav animate-dropdown">
      <div class="container">
        <div class="yamm navbar navbar-default" role="navigation">
          <div class="navbar-header">
         <button data-target="#mc-horizontal-menu-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> 
         <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          </div>
          <div class="nav-bg-class">
            <div class="navbar-collapse collapse" id="mc-horizontal-menu-collapse">
              <div class="nav-outer">
                 
                <!-- /.navbar-nav -->
                <div class="clearfix"></div>
              </div>
              <!-- /.nav-outer --> 
            </div>
            <!-- /.navbar-collapse --> 
            
          </div>
          <!-- /.nav-bg-class --> 
        </div>
        <!-- /.navbar-default --> 
      </div>
      <!-- /.container-class --> 
      
    </div>
    <!-- /.header-nav --> 
    <!-- ============================================== NAVBAR : END ============================================== --> 
    
  </header>

ecom_admin/templates/ecom_admin/register_reseller.html
    {% extends 'ecom_admin/admin_master.html' %}
    {% load static %}
    {% block content %}
    <style>
        table, th, td {
          border:1px solid black;
        }
        </style>
    



    <center><h1 style="color: brown;">REGISTER RESELLERS</center></h1>
    <table border="2" width="100%" >
        
   
        <tr>
            <th>SL.NO</th>
            <TH>ORDER DATE</TH>
            <TH>PRODUCT.NO</TH>
            <TH>PRODUCT NAME</TH>
            <TH>CUSTOMER NAME</TH>
            <TH>MOBILE NO</TH>
            <TH>SHIPPING ADDRESS</TH>
            <TH>QTY</TH>
            <TH>TOTAL AMOUNT</TH>
        </tr>
        <tr>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
            <th>  </th>
        </tr>
        
    </table>

    {% endblock %}